apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: yet-another-lxcfs-webhook
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
